print("My name is Victoria")
print("i am 18 years old")
print("i come from Meru county")
print("i love cooking,painting,drawing and karaoke")
print("-----------")
print("***********")
print("###########")